const { downloadMediaMessage, delay } = require('@whiskeysockets/baileys');

/**
 * Pata picha ya profile kwa usalama na uhakika zaidi
 */
async function getProfilePictureCommand(sock, chatId, msg) {
  try {
    const text = msg.message?.conversation || msg.message?.extendedTextMessage?.text || "";
    const args = text.split(' ');
    const ctx = msg.message?.extendedTextMessage?.contextInfo;

    let targetJids = [];
    
    // 1. Tambua nani anatafutwa (Target Identification)
    if (ctx?.mentionedJid?.length > 0) {
      targetJids = ctx.mentionedJid;
    } else if (ctx?.participant) {
      targetJids = [ctx.participant];
    } else if (args[1] && args[1].match(/^\d+$/)) {
      targetJids = [`${args[1]}@s.whatsapp.net`];
    } else {
      // Kama hakuna tag, chukua picha ya aliyetuma msg
      targetJids = [msg.key.participant || msg.key.remoteJid];
    }

    // 2. Process kila JID kwa umakini
    for (const jid of targetJids.slice(0, 5)) { // Limit to 5 for safety
      await sendEnhancedPP(sock, chatId, jid, msg);
      await delay(1500); // Subiri sekunde 1.5 kuzuia rate limit
    }

  } catch (error) {
    console.error('Error in PP Command:', error);
    await sock.sendMessage(chatId, { text: "❌ Hitilafu imetokea (Error processing request)." });
  }
}

/**
 * Function kuu ya kutuma picha yenye Fallback Logic
 */
async function sendEnhancedPP(sock, chatId, targetJid, quotedMsg) {
  let ppUrl;
  let statusMsg = "";

  try {
    // JARIBIO LA 1: Picha ya HD (High Quality)
    try {
      ppUrl = await sock.profilePictureUrl(targetJid, 'image');
      statusMsg = "✅ HD Quality";
    } catch (e) {
      // JARIBIO LA 2: Picha ya kawaida (Preview/Thumbnail)
      // Mara nyingi picha inakataa HD lakini preview ipo
      try {
        ppUrl = await sock.profilePictureUrl(targetJid, 'preview');
        statusMsg = "⚠️ Standard Quality (HD Restricted)";
      } catch (e2) {
        ppUrl = null;
      }
    }

    // 3. Kama picha haipatikani kabisa (Privacy au No PP)
    if (!ppUrl) {
      // Default placeholder kama picha imefichwa kabisa
      ppUrl = "https://ui-avatars.com/api/?name=No+DP&background=random&size=512";
      statusMsg = "❌ Privacy Restricted / No Bio Picture";
    }

    const name = await getUserName(sock, targetJid);
    const caption = `✨ *PROFILE PICTURE FETCHED* ✨\n\n` +
                    `👤 *User:* @${targetJid.split('@')[0]}\n` +
                    `📝 *Name:* ${name}\n` +
                    `📊 *Status:* ${statusMsg}\n\n` +
                    `_Generated by Bot_`;

    await sock.sendMessage(chatId, {
      image: { url: ppUrl },
      caption: caption,
      mentions: [targetJid]
    }, { quoted: quotedMsg });

  } catch (err) {
    console.log("Final Fallback Error:", err);
  }
}

/**
 * Pata jina la mtumiaji kutoka store au metadata
 */
async function getUserName(sock, jid) {
  try {
    const contact = sock.store?.contacts?.[jid];
    if (contact?.name || contact?.notify) return contact.name || contact.notify;
    
    if (jid.endsWith('@g.us')) {
      const meta = await sock.groupMetadata(jid);
      return meta.subject;
    }
    return "User";
  } catch {
    return "User";
  }
}

module.exports = { getProfilePictureCommand };
