const { generateMessageSourceCode } = require('../lib/messageBuilder');

const sourceCommand = async (sock, chatId, msg, args) => {
    const input = Array.isArray(args) ? args.join(' ').trim() : (args || '').toString().trim();

    if (!input) {
        const snippet = generateMessageSourceCode();
        return sock.sendMessage(chatId, { text: snippet }, { quoted: msg });
    }

    const parts = input.split('|').map(part => part.trim()).filter(Boolean);
    const [title, subtitle, body, footer, ...buttonEntries] = parts;

    const buttons = buttonEntries.map((entry) => {
        const [label, id] = entry.split(',').map(item => item.trim()).filter(Boolean);
        return { label: label || 'Button', id: id || '.menu' };
    });

    const snippet = generateMessageSourceCode({
        title: title || 'MICKEY BOT',
        subtitle: subtitle || 'Message Builder',
        body: body || 'Hello from MICKEY',
        footer: footer || 'Generated by MICKEY',
        buttons,
    });

    return sock.sendMessage(chatId, { text: snippet }, { quoted: msg });
};

sourceCommand.category = 'UTILITY';
sourceCommand.description = 'Generate source code for a simple button message';

module.exports = sourceCommand;
