const crypto = require('crypto');

class ButtonV2 {
    constructor() {
        this._title = '';
        this._subtitle = '';
        this._body = '';
        this._footer = '';
        this._buttons = [];
        this._contextInfo = {};
    }

    setTitle(title) {
        if (typeof title !== 'string') throw new TypeError('Title must be a string');
        this._title = title;
        return this;
    }

    setSubtitle(subtitle) {
        if (typeof subtitle !== 'string') throw new TypeError('Subtitle must be a string');
        this._subtitle = subtitle;
        return this;
    }

    setBody(body) {
        if (typeof body !== 'string') throw new TypeError('Body must be a string');
        this._body = body;
        return this;
    }

    setFooter(footer) {
        if (typeof footer !== 'string') throw new TypeError('Footer must be a string');
        this._footer = footer;
        return this;
    }

    addButton(displayText, buttonId = crypto.randomUUID()) {
        this._buttons.push({
            buttonId,
            buttonText: { displayText },
            type: 1,
        });
        return this;
    }

    async send(sock, jid, { quoted, ...options } = {}) {
        if (!sock || typeof sock.sendMessage !== 'function') {
            throw new Error('A valid socket is required to send the message');
        }

        const message = {
            buttonsMessage: {
                contentText: this._body || '🧩 Message generated by MICKEY',
                footerText: this._footer || 'Powered by MICKEY',
                headerType: 1,
                buttons: this._buttons,
                contextInfo: this._contextInfo,
            },
        };

        return sock.sendMessage(jid, message, { quoted, ...options });
    }
}

function generateMessageSourceCode({
    title = 'MICKEY BOT',
    subtitle = 'Message Builder',
    body = 'Hello from MICKEY',
    footer = 'Generated by MICKEY',
    buttons = [
        { label: 'Open Menu', id: '.menu' },
        { label: 'AI Help', id: '.ai' },
    ],
} = {}) {
    const lines = [];
    lines.push("const { ButtonV2 } = require('./lib/messageBuilder');");
    lines.push('');
    lines.push('const builder = new ButtonV2()');
    lines.push(`    .setTitle(${JSON.stringify(title)})`);
    lines.push(`    .setSubtitle(${JSON.stringify(subtitle)})`);
    lines.push(`    .setBody(${JSON.stringify(body)})`);
    lines.push(`    .setFooter(${JSON.stringify(footer)})`);

    buttons.forEach((button) => {
        lines.push(`    .addButton(${JSON.stringify(button.label)}, ${JSON.stringify(button.id)})`);
    });

    lines.push('');
    lines.push('await builder.send(sock, chatId, { quoted: msg });');

    return [
        '```js',
        ...lines,
        '```',
    ].join('\n');
}

module.exports = {
    ButtonV2,
    generateMessageSourceCode,
};
